# Crowdin Configuration File
project_id: "372633"

files:
  - source: /android/app/src/main/res/values/strings.xml
    translation: /android/app/src/main/res/values-%android_code%/%original_file_name%
    dest: /strings.xml
